services:
  postgres:
    container_name: postgres-sql-aide-budget
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: slim123
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: aide-budget
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped


  mail-dev:
    container_name: mail-dev-aide-budget
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo
    command:
      - "start-dev"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local